import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.geom.AffineTransform;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import javax.imageio.ImageIO;

/**
 * Utility class for producing simple line charts from simulation data and
 * exporting them to PNG or PDF files. The implementation deliberately avoids
 * reliance on third-party libraries, using only core JDK classes. Charts
 * generated by this class are rudimentary but sufficient for visualising
 * trends such as the car speed over time, collision counts and cumulative
 * distance travelled.
 */
public final class GraphGenerator {

    private GraphGenerator() {
        // Utility class; prevent instantiation
    }

    /**
     * Creates a line chart for the provided data. Both the x and y values
     * should be of equal length. The coordinate system is scaled to fit the
     * available width and height, reserving a margin around the edges for
     * axes and labels.
     *
     * @param xData   the independent variable values (typically time)
     * @param yData   the dependent variable values (e.g. speed or distance)
     * @param title   the chart title
     * @param xLabel  label for the x-axis
     * @param yLabel  label for the y-axis
     * @param width   width of the resulting image
     * @param height  height of the resulting image
     * @return a {@link BufferedImage} containing the rendered chart
     */
    public static BufferedImage createLineChart(List<? extends Number> xData,
                                               List<? extends Number> yData,
                                               String title,
                                               String xLabel,
                                               String yLabel,
                                               int width,
                                               int height) {
        if (xData == null || yData == null || xData.size() != yData.size()) {
            throw new IllegalArgumentException("Input data lists must be non-null and of equal length");
        }
        int n = xData.size();
        if (n == 0) {
            // Return blank image if there's no data
            return new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        }

        double minX = Double.MAX_VALUE;
        double maxX = -Double.MAX_VALUE;
        double minY = Double.MAX_VALUE;
        double maxY = -Double.MAX_VALUE;
        for (int i = 0; i < n; i++) {
            double x = xData.get(i).doubleValue();
            double y = yData.get(i).doubleValue();
            if (x < minX) minX = x;
            if (x > maxX) maxX = x;
            if (y < minY) minY = y;
            if (y > maxY) maxY = y;
        }

        // If values are constant, avoid division by zero
        if (minX == maxX) {
            maxX = minX + 1;
        }
        if (minY == maxY) {
            maxY = minY + 1;
        }

        int margin = 50;
        BufferedImage img = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = img.createGraphics();
        g2d.setColor(Color.WHITE);
        g2d.fillRect(0, 0, width, height);
        // Enable antialiasing for smoother lines and text
        g2d.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                              java.awt.RenderingHints.VALUE_ANTIALIAS_ON);

        // Draw title
        g2d.setColor(Color.BLACK);
        Font titleFont = new Font("SansSerif", Font.BOLD, 16);
        g2d.setFont(titleFont);
        FontMetrics titleMetrics = g2d.getFontMetrics();
        int titleWidth = titleMetrics.stringWidth(title);
        g2d.drawString(title, (width - titleWidth) / 2, margin / 2);

        // Axes
        int chartWidth = width - 2 * margin;
        int chartHeight = height - 2 * margin;
        int originX = margin;
        int originY = height - margin;
        g2d.setStroke(new BasicStroke(1.5f));
        g2d.drawLine(originX, originY, originX + chartWidth, originY); // x axis
        g2d.drawLine(originX, originY, originX, originY - chartHeight); // y axis

        // Labels
        Font labelFont = new Font("SansSerif", Font.PLAIN, 12);
        g2d.setFont(labelFont);
        FontMetrics labelMetrics = g2d.getFontMetrics();
        // x label
        int xLabelWidth = labelMetrics.stringWidth(xLabel);
        g2d.drawString(xLabel, originX + (chartWidth - xLabelWidth) / 2,
                       height - margin / 4);
        // y label (rotate 90 degrees)
        int yLabelWidth = labelMetrics.stringWidth(yLabel);
        AffineTransform orig = g2d.getTransform();
        g2d.rotate(-Math.PI / 2);
        g2d.drawString(yLabel, -originY + (chartHeight - yLabelWidth) / 2, margin / 3);
        g2d.setTransform(orig);

        // Draw ticks and grid lines (5 subdivisions)
        int subdivisions = 5;
        g2d.setStroke(new BasicStroke(1f));
        g2d.setColor(new Color(200, 200, 200));
        Font tickFont = new Font("SansSerif", Font.PLAIN, 10);
        g2d.setFont(tickFont);
        FontMetrics tickMetrics = g2d.getFontMetrics();
        for (int i = 0; i <= subdivisions; i++) {
            // x axis ticks
            double xVal = minX + i * (maxX - minX) / subdivisions;
            int xPos = originX + (int) ((xVal - minX) * chartWidth / (maxX - minX));
            g2d.setColor(new Color(220, 220, 220));
            g2d.drawLine(xPos, originY, xPos, originY - chartHeight);
            g2d.setColor(Color.BLACK);
            String tickLabel = String.format("%.2f", xVal);
            int strWidth = tickMetrics.stringWidth(tickLabel);
            g2d.drawString(tickLabel, xPos - strWidth / 2, originY + 15);

            // y axis ticks
            double yVal = minY + i * (maxY - minY) / subdivisions;
            int yPos = originY - (int) ((yVal - minY) * chartHeight / (maxY - minY));
            g2d.setColor(new Color(220, 220, 220));
            g2d.drawLine(originX, yPos, originX + chartWidth, yPos);
            g2d.setColor(Color.BLACK);
            String yTickLabel = String.format("%.2f", yVal);
            int yLabelWidth2 = tickMetrics.stringWidth(yTickLabel);
            g2d.drawString(yTickLabel, originX - yLabelWidth2 - 5, yPos + tickMetrics.getHeight() / 2 - 4);
        }

        // Draw the line chart
        g2d.setColor(Color.BLUE);
        g2d.setStroke(new BasicStroke(2f));
        int prevX = originX + (int) ((xData.get(0).doubleValue() - minX) * chartWidth / (maxX - minX));
        int prevY = originY - (int) ((yData.get(0).doubleValue() - minY) * chartHeight / (maxY - minY));
        for (int i = 1; i < n; i++) {
            int currX = originX + (int) ((xData.get(i).doubleValue() - minX) * chartWidth / (maxX - minX));
            int currY = originY - (int) ((yData.get(i).doubleValue() - minY) * chartHeight / (maxY - minY));
            g2d.drawLine(prevX, prevY, currX, currY);
            prevX = currX;
            prevY = currY;
        }

        g2d.dispose();
        return img;
    }

    /**
     * Saves a buffered image to disk as a PNG file. If the target file already
     * exists it will be silently overwritten.
     *
     * @param image the image to persist
     * @param file  the destination file (including extension)
     * @throws IOException if writing fails
     */
    public static void saveAsPNG(BufferedImage image, File file) throws IOException {
        // Ensure parent directories exist
        if (file.getParentFile() != null) {
            file.getParentFile().mkdirs();
        }
        ImageIO.write(image, "png", file);
    }

    /**
     * Persists a buffered image into a very simple PDF document. The produced
     * file contains a single page sized to the dimensions of the image. The
     * image itself is encoded as a JPEG and embedded directly into the page.
     *
     * <p>This implementation writes the PDF manually to avoid any external
     * dependencies. It is minimalist and does not attempt to implement the
     * entirety of the PDF specification - rather, it produces a valid file
     * sufficient for simple image embedding. Should any error occur during
     * writing, an {@link IOException} is thrown.</p>
     *
     * @param image the image to embed
     * @param file  the destination PDF file (including extension)
     * @throws IOException if an I/O error occurs
     */
    public static void saveAsPDF(BufferedImage image, File file) throws IOException {
        // Convert image to JPEG bytes
        ByteArrayOutputStream imgOut = new ByteArrayOutputStream();
        ImageIO.write(image, "jpg", imgOut);
        imgOut.flush();
        byte[] imgBytes = imgOut.toByteArray();
        imgOut.close();

        int imgWidth = image.getWidth();
        int imgHeight = image.getHeight();

        List<byte[]> objects = new ArrayList<>();
        List<Integer> offsets = new ArrayList<>();

        // Helper to append objects and remember their offset later
        // We'll fill offsets later once we know each object's start

        // Object 1: catalog
        String obj1 = "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n";
        objects.add(obj1.getBytes(StandardCharsets.US_ASCII));

        // Object 2: pages
        String obj2 = "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n";
        objects.add(obj2.getBytes(StandardCharsets.US_ASCII));

        // Object 3: page with resources and content
        StringBuilder pageBuilder = new StringBuilder();
        pageBuilder.append("3 0 obj\n");
        pageBuilder.append("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ")
                   .append(imgWidth).append(' ').append(imgHeight)
                   .append("] /Resources << /XObject << /Im1 4 0 R >> /ProcSet [/PDF /ImageC] >> /Contents 5 0 R >> >>\n");
        pageBuilder.append("endobj\n");
        objects.add(pageBuilder.toString().getBytes(StandardCharsets.US_ASCII));

        // Object 4: image XObject with JPEG data
        ByteArrayOutputStream imgObjectStream = new ByteArrayOutputStream();
        imgObjectStream.write(String.format(
                "4 0 obj\n<< /Type /XObject /Subtype /Image /Width %d /Height %d /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length %d >>\nstream\n",
                imgWidth, imgHeight, imgBytes.length).getBytes(StandardCharsets.US_ASCII));
        imgObjectStream.write(imgBytes);
        imgObjectStream.write("\nendstream\nendobj\n".getBytes(StandardCharsets.US_ASCII));
        objects.add(imgObjectStream.toByteArray());

        // Object 5: content stream that paints the image
        String content = String.format("q\n%d 0 0 %d 0 0 cm\n/Im1 Do\nQ\n", imgWidth, imgHeight);
        byte[] contentBytes = content.getBytes(StandardCharsets.US_ASCII);
        String header5 = String.format("5 0 obj\n<< /Length %d >>\nstream\n", contentBytes.length);
        ByteArrayOutputStream contentStream = new ByteArrayOutputStream();
        contentStream.write(header5.getBytes(StandardCharsets.US_ASCII));
        contentStream.write(contentBytes);
        contentStream.write("endstream\nendobj\n".getBytes(StandardCharsets.US_ASCII));
        objects.add(contentStream.toByteArray());

        // Now assemble the PDF
        try (FileOutputStream fos = new FileOutputStream(file)) {
            // Write the PDF header. The second line in a PDF file is
            // conventionally a comment containing at least one binary
            // character to signal that the file may contain binary data. We
            // avoid non-ASCII characters here for source compatibility and
            // instead rely on the PDF parser tolerating the absence of
            // high-bit characters.
            String header = "%PDF-1.4\n";
            fos.write(header.getBytes(StandardCharsets.US_ASCII));
            // Keep track of the byte count so far. Since we don't emit a
            // binary comment line, the offset is simply the length of the header.
            long offset = header.getBytes(StandardCharsets.US_ASCII).length;
            // Write each object and record its offset
            for (byte[] obj : objects) {
                offsets.add((int) offset);
                fos.write(obj);
                offset += obj.length;
            }
            // xref table
            int objCount = objects.size() + 1;
            long xrefStart = offset;
            fos.write("xref\n".getBytes(StandardCharsets.US_ASCII));
            fos.write(String.format("0 %d\n", objCount).getBytes(StandardCharsets.US_ASCII));
            // object 0
            fos.write("0000000000 65535 f \n".getBytes(StandardCharsets.US_ASCII));
            // object offsets
            for (int off : offsets) {
                fos.write(String.format("%010d 00000 n \n", off).getBytes(StandardCharsets.US_ASCII));
            }
            // trailer
            fos.write("trailer\n".getBytes(StandardCharsets.US_ASCII));
            fos.write(String.format("<< /Size %d /Root 1 0 R >>\n", objCount).getBytes(StandardCharsets.US_ASCII));
            fos.write("startxref\n".getBytes(StandardCharsets.US_ASCII));
            fos.write(String.format("%d\n", xrefStart).getBytes(StandardCharsets.US_ASCII));
            fos.write("%%EOF".getBytes(StandardCharsets.US_ASCII));
        }
    }

    /**
     * Creates and saves all three graphs (speed vs. time, collisions vs. time
     * and cumulative distance vs. time) to disk in both PNG and PDF formats.
     * The files will be named according to the metric they represent. If the
     * output directory does not exist it will be created.
     *
     * @param stats       simulation statistics to visualise
     * @param outputDir   directory into which the files should be written
     * @throws IOException if any export fails
     */
    public static void exportAllGraphs(SimulationStatistics stats, File outputDir) throws IOException {
        if (stats == null) {
            throw new IllegalArgumentException("Statistics object must not be null");
        }
        if (outputDir == null) {
            outputDir = new File("graphs");
        }
        if (!outputDir.exists()) {
            outputDir.mkdirs();
        }
        // Retrieve data
        List<Double> times = stats.getTimeSeries();
        List<Double> speeds = stats.getSpeedSeries();
        List<Integer> collisions = stats.getCollisionSeries();
        List<Double> distances = stats.getDistanceSeries();

        // Generate each chart with a default size
        int width = 600;
        int height = 400;

        BufferedImage speedImg = createLineChart(times, speeds, "Speed vs. Time", "Time (s)", "Speed", width, height);
        BufferedImage collisionImg = createLineChart(times, toDoubleList(collisions), "Collisions vs. Time", "Time (s)", "Collisions", width, height);
        BufferedImage distanceImg = createLineChart(times, distances, "Distance vs. Time", "Time (s)", "Distance", width, height);

        // Save as PNG
        saveAsPNG(speedImg, new File(outputDir, "speed_vs_time.png"));
        saveAsPNG(collisionImg, new File(outputDir, "collisions_vs_time.png"));
        saveAsPNG(distanceImg, new File(outputDir, "distance_vs_time.png"));

        // Save as PDF
        saveAsPDF(speedImg, new File(outputDir, "speed_vs_time.pdf"));
        saveAsPDF(collisionImg, new File(outputDir, "collisions_vs_time.pdf"));
        saveAsPDF(distanceImg, new File(outputDir, "distance_vs_time.pdf"));
    }

    /**
     * Helper method to convert a list of integers into a list of doubles. This
     * is necessary because our charting methods operate on lists of numbers.
     *
     * @param ints the integer list
     * @return a list of doubles with the same numeric values
     */
    static List<Double> toDoubleList(List<Integer> ints) {
        List<Double> doubles = new ArrayList<>(ints.size());
        for (Integer i : ints) {
            doubles.add(i == null ? 0.0 : i.doubleValue());
        }
        return doubles;
    }
}